"""
Milestone 5 Orchestration Contracts

Defines the absolute boundary interfaces and data models for multi-agent coordination.
"""

from typing import Protocol, List, Dict, Any, Optional
from dataclasses import dataclass, field
from enum import Enum
import uuid
import time

# --- ENUMS ---

class AgentStatus(Enum):
    SPAWNING = "SPAWNING"
    READY = "READY"
    IDLE = "IDLE"
    BUSY = "BUSY"
    CHECKPOINTING = "CHECKPOINTING"
    PAUSED = "PAUSED"
    DRAINING = "DRAINING"
    FAILED = "FAILED"
    OFFLINE = "OFFLINE"

class RuntimeLifecycleStatus(Enum):
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

# --- CONTRACTS ---

@dataclass(frozen=True)
class TaskContract:
    """The formal specification of work assigned to a worker."""
    task_id: str
    goal: str
    execution_context: Dict[str, Any] = field(default_factory=dict)
    policy_overrides: Dict[str, Any] = field(default_factory=dict)
    deadline_ms: int = 0
    expected_evidence: str = ""

@dataclass
class RuntimeResult:
    """The rich output generated by a worker execution."""
    task_id: str
    status: RuntimeLifecycleStatus
    produced_evidence: Any = None
    produced_artifacts: List[str] = field(default_factory=list)
    journal_reference: str = ""
    cost_usd: float = 0.0
    metrics: Dict[str, Any] = field(default_factory=dict)
    checkpoint_id: Optional[str] = None
    failure_reason: Optional[str] = None

class IAgentRuntime(Protocol):
    """The Black-Box execution boundary for a worker."""
    
    async def execute(self, task: TaskContract) -> RuntimeResult:
        """Starts or resumes execution of a task."""
        ...
        
    async def pause(self) -> None:
        """Interrupts execution safely."""
        ...
        
    async def resume(self) -> None:
        """Resumes from a paused state."""
        ...
        
    async def checkpoint(self) -> str:
        """Forces an explicit checkpoint and returns the ID."""
        ...
        
    async def cancel(self) -> None:
        """Hard aborts the execution."""
        ...
        
    async def status(self) -> RuntimeLifecycleStatus:
        """Returns the current tactical state of the runtime loop."""
        ...

# --- REGISTRY & METADATA ---

@dataclass(frozen=True)
class AgentDescriptor:
    """Static metadata characterizing a worker's capabilities."""
    agent_id: str
    agent_profile: str               
    agent_capabilities: frozenset[str]
    agent_resource_limits: Dict[str, float]
    agent_supported_contract_versions: frozenset[str]

@dataclass
class AgentHeartbeat:
    """Dynamic state telemetry updated frequently."""
    agent_id: str
    status: AgentStatus
    cpu_usage_pct: float
    memory_usage_mb: float
    queue_depth: int
    health_score: float
    last_seen_timestamp: float = field(default_factory=time.time)

# --- ASSIGNMENT & LEASING ---

@dataclass
class Assignment:
    """Binds a task to a specific worker for a set duration."""
    assignment_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    worker_id: str = ""
    task_id: str = ""
    lease_expiration_timestamp: float = 0.0
    priority: int = 1
    attempt_number: int = 1
