"""
Decision Domain Object

Represents the explicit intent generated by the ReasoningEngine.
This structure strictly replaces raw LLM string outputs, making the reasoning
pipeline fully observable and typed.
"""

import logging
from dataclasses import dataclass
from typing import List, Optional, Dict, Any

log = logging.getLogger(__name__)

@dataclass
class ActionDefinition:
    """Defines the specific action the agent intends to take."""
    action_type: str  # e.g., READ, SEARCH, WRITE, COMPLETE
    parameters: Dict[str, Any]

@dataclass
class ActionDecision:
    """The structured output of a Reasoning cycle."""
    hypothesis: str
    confidence: float
    chosen_action: ActionDefinition
    reason: str
    expected_evidence: str
    expected_observation: str
    exit_condition: str
    alternatives: List[str]

    def __post_init__(self):
        log.info(f"[ActionDecision] Created ActionDecision to perform Action: {self.chosen_action.action_type} (Confidence: {self.confidence:.2f})")
        log.info(f"[ActionDecision] Reason: {self.reason}")
        log.info(f"[ActionDecision] Expected Obs: {self.expected_observation}")
